### ISSUE TITLE
IK:ify twists legs strangely with game rig

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman-plugin-for-blender#10]
Clicking the convert to IK button twists the legs into a kind of unnatural position when used on the game engine rig.

The arms are slightly twisted too, but it doesn't look unnatural.

Before clicking button:

![iktwistbefore](https://cloud.githubusercontent.com/assets/10105480/17166932/4f943ecc-53da-11e6-9211-f64acd768bbd.png)

After clicking button: 

![iktwistafter](https://cloud.githubusercontent.com/assets/10105480/17166936/54835cba-53da-11e6-80e4-18cc97284d32.png)

**Comment by Palmer-JC** [comment]
I have not noticed such a dramatic change.  MHX2 format has none.  Collada pipeline has too many problems to take seriously.  The face on Default rig is mutilated.  All the leaf bones are very very small.  I reported [this](http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=13415).

For game rig the root leaf, toes, head, etc look completely different than they do with MHX2 or in mh.  The root is even vertical.  I could use this to detect Collada and report an error instead of performing.  Better to fix these tiny bones in export / import.
![selection_227](https://cloud.githubusercontent.com/assets/7916131/17179470/63d00b5c-53e7-11e6-98ea-d2ca527919e2.png)

**Comment by joepal1976** [comment]
This issue isn't visible in the current master. Going to assume it went away as a side effect of something we did in the meantime.
