### ISSUE TITLE
Startup Impact

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman-plugin-for-blender#15]
Windows 10 with Release MH 1.1.0

I notice that on startup there is about a 15 second delay that appears to be associated with plugin 8 loading.   During this time the progress bar is frozen at approximately 50% completion.  The task manager did not yet show MH, so i could not figure out how kill MH and use the logs to tell me where this is occurring..   I believe (not positive) that this is new since the Sun, 12-18-2016 update.

Strangely, my MakeHuman-Hg version seems less impated, and the startup delay may have gotten even shorter after running compile_models.py, compille_proxies.py, and compile_targets.py.   The same utilities are not immediately available for the release version, but startup delays like this can often mean that assets are being compiled. Is there any way that that be happening here?

**Comment by joepal1976** [comment]
My spontaneous guess is that this is because 8_community_assets now scans through all assets to exclude already downloaded ones from the list for the asset downloader. 

If this is the case, maybe the results could be cached or something. 

But first step would probably be detect exactly where things happen.

**Comment by CKY-** [comment]
Joe, You are correct, I was Looking at possibly using an external file to store the date users download what file however I still think this will negatively impact the load time of the plugin its self.

**Comment by joepal1976** [comment]
Since the plugin already reads the cached list of downloaded assets from ~/makehuman/v1/data/community-assets/assets.json, maybe we could merge these two functions? I.e, maintain another key in each entry in that file for whether an asset has been downloaded (and when)?

Downside is that the synchronization function would need to be reworked a bit, since currently it simply downloads the json from the server and overwrites the local file.

**Comment by joepal1976** [comment]
This is no longer relevant, and the asset downloader has moved to a separate repo.
