### ISSUE TITLE
Support loading a complete human from MH

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman-plugin-for-blender#30]
I've started adding functionality for loading a complete human via the socket, thus voiding first having to export/import.

At the point of writing this, vertices and faces are correctly imported. 

The code is in the feature branch _import_full_human_binary

It is also important to note that for this to work, the MH side needs:

* The latest MHAPI
* The py3 version of MH from github (or the build with MHAPI replaced with the latest version)
* 8_server_socket code which is for now in a separate feature branch _feature_support_binary_transfers. 

The reason for the requirements is that I've also dropped support for py2 and the 1.1.1 release of MH in the socket code now, making the changes breaking.

**Comment by joepal1976** [comment]
I've posted a status update here: http://www.makehumancommunity.org/forum/viewtopic.php?f=15&t=16684

Executive summary is that I've gotten most things regarding meshes (both on human obj and clothes etc) to load, and that next step is trying to load skeleton and weight painting etc.

I don't think I'll bother with trying to make anything work in BI. Currently I'm only testing with cycles and using principled as central node.

**Comment by Palmer-JC** [comment]
Couple of things, the 2 DLL's should be moved into source & the .ignore entry removed so other people can do a full build without screwing around.  You can suck them out of their repo or the master branches .zip.  I can do it too, but would have to wait until you merge, since edited .ignore in your branch.

Also, please set version to 2.79, so at some point we will already have a .zip, before making the breaking changes for 2.80.  It was set to 2.77, but principled will take it to 2.79.  Blender has no subscription like 3DSMax, so anyone can upgrade at no cost.

**Comment by joepal1976** [comment]
I think this works as intended.
