### ISSUE TITLE
Support blender 2.80

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman-plugin-for-blender#31]
Just creating a meta-issue for now, as the python API for 2.80 still isn't stabilized nor documented. In the recently published roadmap for the beta, it says the API should be finshed:ish in a few weeks. 

Open question: is it viable to support 2.79 and 2.80 in the same code branch, or would it turn the code into an ifdef-riddled utter mess?

I still haven't really taken a look at the 2.80 API.

**Comment by Palmer-JC** [comment]
Since 2.79 is going to fade off into the distance, think just concentrating on finishing functionality using 2.79 is the best use of time.  If completed, keeping 2 way code would not be required, only the last zip for people still on 2.79.

I just set the version to 2.80, got it to load both ways, then made changes where they got more strict with named arguments.  When I got to a breaking change, usually I did not what to do without any API docs.  There I just made some comments, like 'does not work for 2.80'.

Good part is some things work without change.

Would not consider the 'couple of weeks till done thing' to be real.  It is not going to production for a while, 2019.  Get everything wanted done quick enough, & don't have to care or 2 way code.

**Comment by Palmer-JC** [comment]
Also, could at some point make a 2.79 branch, keep master for 2.80, and never merge it.  Keeps options open.  Nuke 2.79 branch eventually.

**Comment by joepal1976** [comment]
I've made some initial swipes at supporting blender 2.80. It didn't take that much to get at least the import-over-socket functionality to work in both 2.79 and 2.80 in the same code. But I didn't even start checking the rig stuff etc. 

I'm created a new branch https://github.com/makehumancommunity/makehuman-plugin-for-blender/tree/_feature_blender_28 for this. It is branched off https://github.com/makehumancommunity/makehuman-plugin-for-blender/tree/_feature_refactor_code_structure, and I'll wait with merging anything to master until we've done something about https://github.com/makehumancommunity/makehuman-plugin-for-blender/issues/38

**Comment by joepal1976** [comment]
This is now merged to master. We can open new issues when and if we find something in specific which does not work with blender 2.80.

**Comment by Palmer-JC** [comment]
FYI, I just found preliminary [API doc for 2.80](https://docs.blender.org/api/blender2.8/).  I can see a couple of solutions in Kinect area, which did not know before.

Also, anything doing matrix multiplication needs to switch from '*' to '@'.  Other useful changes noted [here ](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API)
