### ISSUE TITLE
Overhaul the interface

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman-plugin-for-blender#50]
Some presets sound strange:
General:
"Settings below"  --> "Default Settings"?
Helpers:
"Leave Be" --> "Unchanged" / "Unmodified"?
Import Meshes:
"Only import body" --> "Body"?
"Body+bodyparts" --> "Body, Bodyparts"?
"Body,parts,clothes" --> "Body, Bodyparts, Clothes"?
 "When proxy, mask base mesh" --> "Proxy masks base mesh"?

For MakeClothes getting a body without clothes and detailed helpers, no subdiv would be ideal. Switching general presets does not really have an effect. Switching to MakeClothes settings and changing settings to "Only import body" and Helpers " Leave be" imports a dressed mesh with deleted helpers.

Create different materials for helpers

Allow user defined presets.

**Comment by joepal1976** [comment]
"Settings below" means "use the settings you change in the UI below this drop-down", as opposed to "use a predefined set of settings" (such as what is appropriate for MakeClothes). 

The theory is that using the MakeClothes preset should override whatever is set in the UI. 

But I agree that the language could be improved significantly, with your suggestions as a starting point.

**Comment by joepal1976** [comment]
All in all, I'm thinking a more radical restructuring is in order. 

It should be possible to have multiple presets, also user defined ones. As is shown in #45, it's perfectly possible to have different preferences for what the defaults should be.

I'll open a feature branch for this and do some basic code wrestling.

**Comment by joepal1976** [comment]
I've now restructured the UI so that:

- importer settings are on a separate tab
- the dropdown for what settings to use refer to a preset
- presets can be loaded and saved

Obviously more can be done about the looks and wording, particularly on the first panel. But for now I'm thinking that operations being visible per default and settings being put on a panel you can go look for makes more sense. 

All these changes are currently in this feature branch: https://github.com/makehumancommunity/makehuman-plugin-for-blender/tree/_feature_restructure_interface

This is how the UI looks right now:

![ui_restructure](https://user-images.githubusercontent.com/10105480/60514712-52f37000-9cda-11e9-96fd-ff9dab73667c.png)
